### ISSUE TITLE
svg output does not work wouthout Graph::Easy::As_svg

### ISSUE THREAD

**Issue by bjakubski** [neilb/App-PrereqGrapher#7]
Graph::Easy::As_svg is an 'recommends' dependency of Graph::Easy, so by default it is _not_ installed i.e. with cpanm.
Currently prereq-grapher scans all the modules and at the end fails with:

    Can't locate Graph/Easy/As_svg.pm in @INC (@INC contains: (...)

Not sure if this should be 'hard' dependency or maybe 'sugggests' (or even 'recommends').
If this is not 'hard' dep, then probably some earlier and more helpful error message should be in order?

**Comment by neilb** [comment]
I've improved the error message and added a comment about this dependency in the `SEE ALSO`.

Haven't added as an optional prereq -- will think about that and possibly do in a later release :-)

Thanks for reporting this.

Cheers,
Neil
